### ISSUE TITLE
404 no calendar found

### ISSUE THREAD

**Issue by theScrabi** [buzz/ics2owncloud.py#13]
If run the script i get the error:
`HTTPError: 404 Client Error: Not Found for url: https://<cloud>:<port>/owncloud/remote.php/dav/calendars/<user>/<calendar>?export
Traceback (most recent call last):
  File "./ics2owncloud.py", line 78, in <module>
    Config.get(key, 'ics_url'),
  File "./ics2owncloud.py", line 22, in do_import
    r.raise_for_status()
  File "/opt/ics2owncloud/venv/local/lib/python2.7/site-packages/requests/models.py", line 840, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
`

What went wrong?

**Comment by Maxqia** [comment]
Are you using ldap?

**Comment by buzz** [comment]
You got a `404 - Not Found` HTTP response. Double check that your URL is good and your server working.
